# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Usa aspas simples por padrão
Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/StringConcatenation:
  EnforcedStyle: double_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false